<a href="https://colab.research.google.com/github/Burhan1310/Python_learning/blob/main/gradient_calculation_with_autograde.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.7366,  0.7183, -2.2533], requires_grad=True)

In [3]:
y = x + 2
y

tensor([ 2.7366,  2.7183, -0.2533], grad_fn=<AddBackward0>)

In [4]:
z = y * y * 2
z

tensor([14.9780, 14.7781,  0.1283], grad_fn=<MulBackward0>)

In [5]:
z = z.mean()

In [6]:
z.backward()

In [7]:
x.grad

tensor([ 3.6488,  3.6244, -0.3377])

In [8]:
weights = torch.ones(4, requires_grad=True)
weights

tensor([1., 1., 1., 1.], requires_grad=True)

In [29]:
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()

  print(weights.grad)


tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [31]:
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()

  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [32]:
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor