<a href="https://colab.research.google.com/github/Burhan1310/Python_learning/blob/main/tensors_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
torch.__version__

'2.6.0+cu124'

In [5]:
import numpy as np

In [9]:
list = [3, 4, 5, 6]
arr = np.array(list)

In [10]:
arr

array([3, 4, 5, 6])

In [8]:
arr.dtype

dtype('int64')

**Convert Numpy to Pytorch tensors**

In [11]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [12]:
# Indexing similar to numpy
tensors[:2]

tensor([3, 4])

In [13]:
## Disadvantages of from_numpy. The array and tensor uses the same memory location
tensors[3] = 100

In [14]:
tensors

tensor([  3,   4,   5, 100])

In [15]:
arr

array([  3,   4,   5, 100])

In [16]:
### Prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr


tensor([  3,   4,   5, 100])

In [17]:
tensor_arr[3] = 120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120])
[  3   4   5 100]


In [18]:
### zeros and ones
torch.zeros(2,3, dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [19]:
torch.ones(2,3, dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [23]:
a = torch.tensor(np.arange(0,15).reshape(5,3))
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [26]:
a[:,0]

tensor([ 0,  3,  6,  9, 12])

In [27]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])

**Arithmetic** **Operation**

In [28]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [29]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [30]:
c = torch.zeros(3)

In [31]:
c

tensor([0., 0., 0.])

In [32]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [33]:
c

tensor([ 7.,  9., 11.])

In [34]:
torch.add(a,b).sum()

tensor(27.)

**Dot Products and Multiplication Opearation**

In [35]:
x = torch.tensor([3,4,5],dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [37]:
x.mul(y)

tensor([12., 20., 30.])

In [38]:
x.dot(y)

tensor(62.)

**Matrix Multiplication**

In [39]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [40]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [41]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [42]:
x@y

tensor([[55., 53.],
        [90., 92.]])

In [43]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [44]:
%cd /content/drive/MyDrive/Colab Notebooks/deep_learning/

/content/drive/MyDrive/Colab Notebooks/deep_learning


In [51]:
%cd /content/drive/MyDrive/Colab Notebooks/deep_learning
!git clone https://github.com/Burhan1310/Python_learning.git


/content/drive/MyDrive/Colab Notebooks/deep_learning
Cloning into 'Python_learning'...
remote: Enumerating objects: 521, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 521 (delta 8), reused 26 (delta 5), pack-reused 487 (from 1)
Receiving objects: 100% (521/521), 69.05 MiB | 10.93 MiB/s, done.
Resolving deltas: 100% (174/174), done.
Updating files: 100% (478/478), done.


In [52]:
%cd /content/drive/MyDrive/Colab Notebooks/deep_learning/Python_learning

/content/drive/MyDrive/Colab Notebooks/deep_learning/Python_learning


In [53]:
!git add.
!git commit -m "update notebook"
!git push

git: 'add.' is not a git command. See 'git --help'.

The most similar command is
	add
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@8215ad4ed7f1.(none)')
fatal: could not read Username for 'https://github.com': No such device or address
