## Import Libraries

In [23]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression

In [24]:
weight = np.array([2, 4, 5, 3, 6, 5, 7])
price = np.array([35, 60, 20, 50, 50, 55, 60])

## Create DataFrame

In [26]:
df = pd.DataFrame({'weight': weight, 'price': price})
df

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

In [27]:
X = df[['weight']]
y = df[['price']]

In [36]:
model = LinearRegression().fit(X, y)

In [40]:
slope = model.coef_
slope

array([[2.62096774]])

In [42]:
intercept = model.intercept_
intercept

array([35.16129032])

In [48]:
model.predict([[6]])

C:\Users\joy\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[50.88709677]])

In [50]:
X

weight
0       2
1       4
2       5
3       3
4       6
5       5
6       7

In [52]:
y_predicted = model.predict(X)

array([[40.40322581],
       [45.64516129],
       [48.26612903],
       [43.02419355],
       [50.88709677],
       [48.26612903],
       [53.50806452]])

## Create the example dataset

In [61]:
data = {
    'Weight': [2, 4, 5, 3, 6, 5, 7],
    'Price': [35, 60, 20, 50, 50, 55, 60],
    'y_predicted': [40.40, 45.64, 48.26, 43.02, 50.88, 48.26, 53.50]
}

In [65]:
df = pd.DataFrame(data)
df

Weight  Price  y_predicted
0       2     35        40.40
1       4     60        45.64
2       5     20        48.26
3       3     50        43.02
4       6     50        50.88
5       5     55        48.26
6       7     60        53.50

In [73]:
df['Residuals'] = df['Price'] - df['y_predicted']
df

Weight  Price  y_predicted  Residuals
0       2     35        40.40      -5.40
1       4     60        45.64      14.36
2       5     20        48.26     -28.26
3       3     50        43.02       6.98
4       6     50        50.88      -0.88
5       5     55        48.26       6.74
6       7     60        53.50       6.50

## MSE & MAE

In [76]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [78]:
mse = mean_squared_error(df.Price, df.y_predicted)
mse

167.30994285714283