In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 5, 4])

## Create DataFrame

In [6]:
df = pd.DataFrame({'x': x, 'y': y})
df

x  y
0  1  2
1  2  3
2  3  5
3  4  4

In [8]:
X = df[['x']]
y = df[['y']]

## Using Sklearn to perform linear Regression

In [11]:
model = LinearRegression().fit(X,y)

In [13]:
slope_sklearn = model.coef_
slope_sklearn

array([[0.8]])

In [15]:
intercept_sklearn = model.intercept_
intercept_sklearn

array([1.5])

In [17]:
X

x
0  1
1  2
2  3
3  4

In [19]:
model.predict(X)

array([[2.3],
       [3.1],
       [3.9],
       [4.7]])

## Create the example dataset

In [22]:
data = {
    'x': [1, 2, 3, 4],
    'y': [2, 3, 5, 4],
    'y_hat': [2.3, 3.1, 3.9, 4.7] #predicted value of y
}

## Create DataFrame

In [28]:
df = pd.DataFrame(data)
df

x  y  y_hat
0  1  2    2.3
1  2  3    3.1
2  3  5    3.9
3  4  4    4.7

## Calculate Residuals

In [35]:
#adding new column in df named Residuals
df['Residuals'] = df['y'] - df['y_hat']
df

x  y  y_hat  Residuals
0  1  2    2.3       -0.3
1  2  3    3.1       -0.1
2  3  5    3.9        1.1
3  4  4    4.7       -0.7