In [47]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [48]:
nnfs.init()

In [49]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [50]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [51]:
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

In [52]:
X, y = spiral_data(samples=100, classes=3)

In [53]:
dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()

In [54]:
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

In [55]:
dense1.forward(X)
activation1.forward(dense1.output)

In [56]:
dense2.forward(activation1.output)
activation2.forward(dense2.output)

In [57]:
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
