In [52]:
import numpy as np

In [53]:
a = np.array([5,6,7])
a[0]

5

In [54]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [55]:
a = np.array([[1,2],[3,4]])
a.ndim

2

In [56]:
a.itemsize

4

In [57]:
a.dtype

dtype('int32')

In [58]:
a = np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a.itemsize

8

In [59]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [60]:
a.size

6

In [66]:
a[2,0]

5.0

In [11]:
a.shape

(3, 2)

In [13]:
a = np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
l = range(5)
l

range(0, 5)

In [19]:
np.arange(1,5)

array([1, 2, 3, 4])

In [22]:
np.arange(1,6,2)

array([1, 3, 5])

In [23]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [25]:
a.shape

(3, 2)

In [26]:
a.reshape(2,3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [27]:
a.ravel()

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [28]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [29]:
a.min()

(1+0j)

In [30]:
a.max()

(6+0j)

In [31]:
a.sum()

(21+0j)

In [32]:
a.sum(axis=0)

array([ 9.+0.j, 12.+0.j])

In [33]:
a.sum(axis=1)

array([ 3.+0.j,  7.+0.j, 11.+0.j])

In [42]:
a1 = np.array([[1,2],[3,4]])
b1 = np.array([[5,6],[7,8]])

In [43]:
a1

array([[1, 2],
       [3, 4]])

In [44]:
b1

array([[5, 6],
       [7, 8]])

In [45]:
a1+b1

array([[ 6,  8],
       [10, 12]])

In [46]:
a1/b1

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [47]:
a1.dot(b1)

array([[19, 22],
       [43, 50]])