In [2]:
import numpy as np

In [3]:
a = np.array([4,5,6])
a[0:2]

array([4, 5])

In [4]:
a[-1]

6

In [5]:
a1 = np.array([[4,56,4],[2,3,54],[3,54,78]])
a1

array([[ 4, 56,  4],
       [ 2,  3, 54],
       [ 3, 54, 78]])

In [6]:
a1[1,2]

54

In [7]:
a1[0:2,2]

array([ 4, 54])

In [8]:
a1[-1]

array([ 3, 54, 78])

In [9]:
a1[-1,0:2]

array([ 3, 54])

In [10]:
a1[:,1:]

array([[56,  4],
       [ 3, 54],
       [54, 78]])

In [11]:
for row in a1:
    print(row)

[ 4 56  4]
[ 2  3 54]
[ 3 54 78]


In [12]:
for cell in a1.flat:
    print(cell)

4
56
4
2
3
54
3
54
78


In [13]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [17]:
new = np.arange(30).reshape(2,15)
new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [18]:
result = np.hsplit(new,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [19]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [21]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [22]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [26]:
result = np.vsplit(new,2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [27]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [34]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])